# .github/workflows/lint.yml

name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8

      - name: Run Pylint
        run: |
          pylint your_python_file.py

      - name: Run Flake8
        run: |
          flake8 your_python_file.py
